/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alain.monetizacion.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the History service. Represents a row in the &quot;MT_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alain.monetizacion.model.impl.HistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alain.monetizacion.model.impl.HistoryImpl}.
 * </p>
 *
 * @author Alain
 * @see History
 * @see com.alain.monetizacion.model.impl.HistoryImpl
 * @see com.alain.monetizacion.model.impl.HistoryModelImpl
 * @generated
 */
public interface HistoryModel extends BaseModel<History> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a history model instance should use the {@link History} interface instead.
	 */

	/**
	 * Returns the primary key of this history.
	 *
	 * @return the primary key of this history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this history.
	 *
	 * @param primaryKey the primary key of this history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the history ID of this history.
	 *
	 * @return the history ID of this history
	 */
	public long getHistoryId();

	/**
	 * Sets the history ID of this history.
	 *
	 * @param historyId the history ID of this history
	 */
	public void setHistoryId(long historyId);

	/**
	 * Returns the subscription ID of this history.
	 *
	 * @return the subscription ID of this history
	 */
	public long getSubscriptionId();

	/**
	 * Sets the subscription ID of this history.
	 *
	 * @param subscriptionId the subscription ID of this history
	 */
	public void setSubscriptionId(long subscriptionId);

	/**
	 * Returns the paid date of this history.
	 *
	 * @return the paid date of this history
	 */
	public Date getPaidDate();

	/**
	 * Sets the paid date of this history.
	 *
	 * @param paidDate the paid date of this history
	 */
	public void setPaidDate(Date paidDate);

	/**
	 * Returns the last paid of this history.
	 *
	 * @return the last paid of this history
	 */
	public Date getLastPaid();

	/**
	 * Sets the last paid of this history.
	 *
	 * @param lastPaid the last paid of this history
	 */
	public void setLastPaid(Date lastPaid);

	/**
	 * Returns the pending payment of this history.
	 *
	 * @return the pending payment of this history
	 */
	public Date getPendingPayment();

	/**
	 * Sets the pending payment of this history.
	 *
	 * @param pendingPayment the pending payment of this history
	 */
	public void setPendingPayment(Date pendingPayment);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.alain.monetizacion.model.History history);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alain.monetizacion.model.History> toCacheModel();

	@Override
	public com.alain.monetizacion.model.History toEscapedModel();

	@Override
	public com.alain.monetizacion.model.History toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}