/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alain.monetizacion.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PayPal service. Represents a row in the &quot;MT_PayPal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alain.monetizacion.model.impl.PayPalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alain.monetizacion.model.impl.PayPalImpl}.
 * </p>
 *
 * @author Alain
 * @see PayPal
 * @see com.alain.monetizacion.model.impl.PayPalImpl
 * @see com.alain.monetizacion.model.impl.PayPalModelImpl
 * @generated
 */
public interface PayPalModel extends BaseModel<PayPal> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pay pal model instance should use the {@link PayPal} interface instead.
	 */

	/**
	 * Returns the primary key of this pay pal.
	 *
	 * @return the primary key of this pay pal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pay pal.
	 *
	 * @param primaryKey the primary key of this pay pal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the paypal user of this pay pal.
	 *
	 * @return the paypal user of this pay pal
	 */
	@AutoEscape
	public String getPaypalUser();

	/**
	 * Sets the paypal user of this pay pal.
	 *
	 * @param paypalUser the paypal user of this pay pal
	 */
	public void setPaypalUser(String paypalUser);

	/**
	 * Returns the paypal password of this pay pal.
	 *
	 * @return the paypal password of this pay pal
	 */
	@AutoEscape
	public String getPaypalPassword();

	/**
	 * Sets the paypal password of this pay pal.
	 *
	 * @param paypalPassword the paypal password of this pay pal
	 */
	public void setPaypalPassword(String paypalPassword);

	/**
	 * Returns the paypal firm of this pay pal.
	 *
	 * @return the paypal firm of this pay pal
	 */
	@AutoEscape
	public String getPaypalFirm();

	/**
	 * Sets the paypal firm of this pay pal.
	 *
	 * @param paypalFirm the paypal firm of this pay pal
	 */
	public void setPaypalFirm(String paypalFirm);

	/**
	 * Returns the paypal email of this pay pal.
	 *
	 * @return the paypal email of this pay pal
	 */
	@AutoEscape
	public String getPaypalEmail();

	/**
	 * Sets the paypal email of this pay pal.
	 *
	 * @param paypalEmail the paypal email of this pay pal
	 */
	public void setPaypalEmail(String paypalEmail);

	/**
	 * Returns the configuration ID of this pay pal.
	 *
	 * @return the configuration ID of this pay pal
	 */
	public long getConfigurationId();

	/**
	 * Sets the configuration ID of this pay pal.
	 *
	 * @param configurationId the configuration ID of this pay pal
	 */
	public void setConfigurationId(long configurationId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.alain.monetizacion.model.PayPal payPal);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alain.monetizacion.model.PayPal> toCacheModel();

	@Override
	public com.alain.monetizacion.model.PayPal toEscapedModel();

	@Override
	public com.alain.monetizacion.model.PayPal toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}