/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alain.monetizacion.model;

import com.alain.monetizacion.service.persistence.Role_ConfigPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Role_Config service. Represents a row in the &quot;MT_Role_Config&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alain.monetizacion.model.impl.Role_ConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alain.monetizacion.model.impl.Role_ConfigImpl}.
 * </p>
 *
 * @author Alain
 * @see Role_Config
 * @see com.alain.monetizacion.model.impl.Role_ConfigImpl
 * @see com.alain.monetizacion.model.impl.Role_ConfigModelImpl
 * @generated
 */
public interface Role_ConfigModel extends BaseModel<Role_Config> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a role_ config model instance should use the {@link Role_Config} interface instead.
	 */

	/**
	 * Returns the primary key of this role_ config.
	 *
	 * @return the primary key of this role_ config
	 */
	public Role_ConfigPK getPrimaryKey();

	/**
	 * Sets the primary key of this role_ config.
	 *
	 * @param primaryKey the primary key of this role_ config
	 */
	public void setPrimaryKey(Role_ConfigPK primaryKey);

	/**
	 * Returns the role ID of this role_ config.
	 *
	 * @return the role ID of this role_ config
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this role_ config.
	 *
	 * @param roleId the role ID of this role_ config
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the configuration ID of this role_ config.
	 *
	 * @return the configuration ID of this role_ config
	 */
	public long getConfigurationId();

	/**
	 * Sets the configuration ID of this role_ config.
	 *
	 * @param configurationId the configuration ID of this role_ config
	 */
	public void setConfigurationId(long configurationId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.alain.monetizacion.model.Role_Config role_Config);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alain.monetizacion.model.Role_Config> toCacheModel();

	@Override
	public com.alain.monetizacion.model.Role_Config toEscapedModel();

	@Override
	public com.alain.monetizacion.model.Role_Config toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}