/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alain.monetizacion.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Subscription service. Represents a row in the &quot;MT_Subscription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alain.monetizacion.model.impl.SubscriptionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alain.monetizacion.model.impl.SubscriptionImpl}.
 * </p>
 *
 * @author Alain
 * @see Subscription
 * @see com.alain.monetizacion.model.impl.SubscriptionImpl
 * @see com.alain.monetizacion.model.impl.SubscriptionModelImpl
 * @generated
 */
public interface SubscriptionModel extends BaseModel<Subscription> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subscription model instance should use the {@link Subscription} interface instead.
	 */

	/**
	 * Returns the primary key of this subscription.
	 *
	 * @return the primary key of this subscription
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subscription.
	 *
	 * @param primaryKey the primary key of this subscription
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the subscription ID of this subscription.
	 *
	 * @return the subscription ID of this subscription
	 */
	public long getSubscriptionId();

	/**
	 * Sets the subscription ID of this subscription.
	 *
	 * @param subscriptionId the subscription ID of this subscription
	 */
	public void setSubscriptionId(long subscriptionId);

	/**
	 * Returns the user ID of this subscription.
	 *
	 * @return the user ID of this subscription
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this subscription.
	 *
	 * @param userId the user ID of this subscription
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this subscription.
	 *
	 * @return the user uuid of this subscription
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this subscription.
	 *
	 * @param userUuid the user uuid of this subscription
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this subscription.
	 *
	 * @return the create date of this subscription
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this subscription.
	 *
	 * @param createDate the create date of this subscription
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the expire date of this subscription.
	 *
	 * @return the expire date of this subscription
	 */
	public Date getExpireDate();

	/**
	 * Sets the expire date of this subscription.
	 *
	 * @param expireDate the expire date of this subscription
	 */
	public void setExpireDate(Date expireDate);

	/**
	 * Returns the payment of this subscription.
	 *
	 * @return the payment of this subscription
	 */
	public double getPayment();

	/**
	 * Sets the payment of this subscription.
	 *
	 * @param payment the payment of this subscription
	 */
	public void setPayment(double payment);

	/**
	 * Returns the configuration ID of this subscription.
	 *
	 * @return the configuration ID of this subscription
	 */
	public long getConfigurationId();

	/**
	 * Sets the configuration ID of this subscription.
	 *
	 * @param configurationId the configuration ID of this subscription
	 */
	public void setConfigurationId(long configurationId);

	/**
	 * Returns the paypal profile of this subscription.
	 *
	 * @return the paypal profile of this subscription
	 */
	@AutoEscape
	public String getPaypalProfile();

	/**
	 * Sets the paypal profile of this subscription.
	 *
	 * @param paypalProfile the paypal profile of this subscription
	 */
	public void setPaypalProfile(String paypalProfile);

	/**
	 * Returns the is active of this subscription.
	 *
	 * @return the is active of this subscription
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this subscription is is active.
	 *
	 * @return <code>true</code> if this subscription is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this subscription is is active.
	 *
	 * @param isActive the is active of this subscription
	 */
	public void setIsActive(boolean isActive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.alain.monetizacion.model.Subscription subscription);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alain.monetizacion.model.Subscription> toCacheModel();

	@Override
	public com.alain.monetizacion.model.Subscription toEscapedModel();

	@Override
	public com.alain.monetizacion.model.Subscription toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}