/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alain.monetizacion.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Visa service. Represents a row in the &quot;MT_Visa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alain.monetizacion.model.impl.VisaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alain.monetizacion.model.impl.VisaImpl}.
 * </p>
 *
 * @author Alain
 * @see Visa
 * @see com.alain.monetizacion.model.impl.VisaImpl
 * @see com.alain.monetizacion.model.impl.VisaModelImpl
 * @generated
 */
public interface VisaModel extends BaseModel<Visa> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a visa model instance should use the {@link Visa} interface instead.
	 */

	/**
	 * Returns the primary key of this visa.
	 *
	 * @return the primary key of this visa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this visa.
	 *
	 * @param primaryKey the primary key of this visa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the card number of this visa.
	 *
	 * @return the card number of this visa
	 */
	public long getCardNumber();

	/**
	 * Sets the card number of this visa.
	 *
	 * @param cardNumber the card number of this visa
	 */
	public void setCardNumber(long cardNumber);

	/**
	 * Returns the card expire date of this visa.
	 *
	 * @return the card expire date of this visa
	 */
	public Date getCardExpireDate();

	/**
	 * Sets the card expire date of this visa.
	 *
	 * @param cardExpireDate the card expire date of this visa
	 */
	public void setCardExpireDate(Date cardExpireDate);

	/**
	 * Returns the card verification of this visa.
	 *
	 * @return the card verification of this visa
	 */
	public int getCardVerification();

	/**
	 * Sets the card verification of this visa.
	 *
	 * @param cardVerification the card verification of this visa
	 */
	public void setCardVerification(int cardVerification);

	/**
	 * Returns the configuration ID of this visa.
	 *
	 * @return the configuration ID of this visa
	 */
	public long getConfigurationId();

	/**
	 * Sets the configuration ID of this visa.
	 *
	 * @param configurationId the configuration ID of this visa
	 */
	public void setConfigurationId(long configurationId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.alain.monetizacion.model.Visa visa);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.alain.monetizacion.model.Visa> toCacheModel();

	@Override
	public com.alain.monetizacion.model.Visa toEscapedModel();

	@Override
	public com.alain.monetizacion.model.Visa toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}